apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: kubernetes-livereload-article
build:
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05
      timezone: UTC
  artifacts:
    - image: kubernetes-spring-example
      jib: { }
deploy:
  kustomize:
    paths:
      - deployment/overlays/dev
