management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 9000
  endpoint:
    health:
      probes:
        enabled: true
server:
  shutdown: graceful
spring:
  application:
    name: kubernetes-livereload-application
