management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 9000
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: info
    org.hibernate: debug
server:
  shutdown: graceful
spring:
  application:
    name: kubernetes-livereload-application
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin123
