apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: dev
namePrefix: dev-

configMapGenerator:
  - name: application-config
    files:
      - configs/application.yaml

resources:
  - ../../base