apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deployment
  labels:
    app: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
        - name: k8s-application
          image: kubernetes-spring-example
          livenessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 9000
              path: /actuator/health/readiness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: application-config