apiVersion: v1
kind: Service
metadata:
  name: client-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      name: app-port
  selector:
    app: k8s-app